project:
  type: website

website:
  title: "Moaaz Alqady"
  navbar:
    background: "#0D7758"
    left:
      - href: research.qmd
        text: Research
      - href: talks.qmd
        text: Talks
      - href: teaching.qmd
        text: Teaching
      - href: outreach.qmd
        text: Outreach
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    link-external-newwindow: true